USE [master]
GO

/****** Object:  Database [Cinema]    Script Date: 02/06/2018 21:46:19 ******/
CREATE DATABASE [Cinema] ON  PRIMARY 
( NAME = N'Cinema', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Cinema.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Cinema_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Cinema_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Cinema] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cinema].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cinema] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cinema] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cinema] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cinema] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cinema] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cinema] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cinema] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Cinema] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cinema] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cinema] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cinema] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cinema] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cinema] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cinema] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cinema] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cinema] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cinema] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cinema] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cinema] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cinema] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cinema] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cinema] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cinema] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cinema] SET  READ_WRITE 
GO

ALTER DATABASE [Cinema] SET RECOVERY FULL 
GO

ALTER DATABASE [Cinema] SET  MULTI_USER 
GO

ALTER DATABASE [Cinema] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cinema] SET DB_CHAINING OFF 
GO

