//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_mini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema_Staff
    {
        public int id_nv { get; set; }
        public int type_staff { get; set; }
        public string name { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
    }
}
