//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_mini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cinema_Staff()
        {
            this.Cinema_Ticket = new HashSet<Cinema_Ticket>();
            this.Cinema_WorkingPlan = new HashSet<Cinema_WorkingPlan>();
        }
    
        public int id { get; set; }
        public int type_staff { get; set; }
        public string name { get; set; }
        public int phone { get; set; }
        public string address { get; set; }
        public string status { get; set; }
    
        public virtual Cinema_Type_Staff Cinema_Type_Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cinema_Ticket> Cinema_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cinema_WorkingPlan> Cinema_WorkingPlan { get; set; }
    }
}
