//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_mini.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinema_Film> Cinema_Film { get; set; }
        public virtual DbSet<Cinema_Popcorn> Cinema_Popcorn { get; set; }
        public virtual DbSet<Cinema_Room> Cinema_Room { get; set; }
        public virtual DbSet<Cinema_Showtime> Cinema_Showtime { get; set; }
        public virtual DbSet<Cinema_Staff> Cinema_Staff { get; set; }
        public virtual DbSet<Cinema_Ticket> Cinema_Ticket { get; set; }
        public virtual DbSet<Cinema_Type_Staff> Cinema_Type_Staff { get; set; }
        public virtual DbSet<Cinema_TypeFilm> Cinema_TypeFilm { get; set; }
        public virtual DbSet<Cinema_TypeTick> Cinema_TypeTick { get; set; }
        public virtual DbSet<Cinema_User> Cinema_User { get; set; }
        public virtual DbSet<Cinema_Usertype> Cinema_Usertype { get; set; }
        public virtual DbSet<Cinema_WorkingPlan> Cinema_WorkingPlan { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Cinema_Film_TypeFilm> Cinema_Film_TypeFilm { get; set; }
    }
}
