//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_mini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema_WorkingPlan
    {
        public int id { get; set; }
        public int id_staff { get; set; }
        public int check_in { get; set; }
        public int check_out { get; set; }
        public int actual_wkd { get; set; }
        public int standard_salary { get; set; }
    }
}
