//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_mini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema_TrackingLogin
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime time_created { get; set; }
        public System.DateTime duration_expired { get; set; }
        public string username { get; set; }
    }
}
