//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_mini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_ticket
    {
        public int id { get; set; }
        public int id_pc { get; set; }
        public int id_sc { get; set; }
        public int id_user { get; set; }
        public int id_type_tick { get; set; }
        public int id_film { get; set; }
        public string PC_Name { get; set; }
        public string SC_Name { get; set; }
        public string username { get; set; }
        public string TT_Name { get; set; }
        public string FI_Name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public int id_nv { get; set; }
        public string ST_Name { get; set; }
    }
}
