//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_mini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_get_film_data
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string id_type_film { get; set; }
        public string name_type_film { get; set; }
        public System.DateTime created_date { get; set; }
    }
}
